data :
  PETA:
    data_dir: "C:/Users/wolve/arsim/gender-classification-1/dataset/PETA/PETAdataset"
    height : 224
    width : 224

mlflow:
  tracking_uri: "http://localhost:5000" # MLflow tracking server URI
  experiment_name: "PETAdataset_classification_hypertun_only3"
  log_every_n_step: 100 # PyTorch autologging

train:
  num_epochs: 10
  log_every_n_steps: 16
  limit_val_batches: 50
  check_val_every_n_epoch: 1
  num_workers: 4

valid:
  num_workers: 2

ray:
  storage_path: "E:/sim/gender-classification/ray_results"
  max_failures : 2  # Occurs InvalidStateError (not-used)
  run_name: "tune_p"
  scheduler: # Early stopping scheduler
    max_t: 100
    grace_period: 10
    reduction_factor: 2
  tune:
    metric: "val_loss"
    mode: "min"
    num_samples: 3  # Number of times to sample from the hyperparameter space
    max_concurrent_trials: 1 # Maximum number of trials to run concurrently
  resources:
    cpus_per_trial: 4.0
    gpus_per_trial: 1.0

hyperparameters:
  model_name: 
    # - convnext_nano
    # - resnet50
    - vgg16
    - vit_small_patch8_224_dino
    # - deit_small_patch16_224
  lr: 
    min : 0.0001 # 1e-4
    max : 0.01 # 1e-2 
  batch_size :
    - 8
    # - 16
  optimizer: 
    - adam
  augment_data: True # [ True or False ] . The default is False(no_augment). If True then augmentation and no_augmentation grid_search.